apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80       # Port yang digunakan oleh service
      targetPort: 3000  # Port yang digunakan oleh aplikasi di dalam container
      nodePort: 30080  # Port yang akan digunakan di node untuk akses eksternal
  type: NodePort  # Ubah dari LoadBalancer menjadi NodePort
